# ======================
# CI Stages
# ======================

stages:
    - build

# ======================
# Build app image
# ======================

build application image:
    image: docker:latest
    stage: build
    only:
        - master
    services:
        - docker:dind
    before_script:
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab.enrise.com:5005
    script:
        - docker build -t gitlab.enrise.com:5005/enrise/gcloudkubebox:latest .
        - docker push gitlab.enrise.com:5005/enrise/gcloudkubebox:latest